---
README.md:
    name: "auth-service-provider"
    minor_version: "0.1"
    badges:
        - "[![Build Status](http://drone.etna-alternance.net/github.com/etna-alternance/composer-acl-service-provider/status.svg?branch=master)](http://drone.etna-alternance.net/github.com/etna-alternance/composer-auth-service-provider)"
        - "[![Dependency Status](https://www.versioneye.com/user/projects/53dde6f38e78abc19100004d/badge.svg)](https://www.versioneye.com/user/projects/53dde6f38e78abc19100004d)"
